### ISSUE TITLE
Create Bowling Pins Blender Mesh

### ISSUE THREAD

**Issue by Ean-Warrick** [Ean-Warrick/Roll-A-Ball#1]
Create a bowling pin mesh for the game in blender

**Comment by Dan-um** [comment]
Created first mesh. Sculpted but untextured.

**Comment by Dan-um** [comment]
Created a second mesh with added colors and textures.

**Comment by Dan-um** [comment]
I am quite bad at working with git but I have my bowling pin in the main branch, sorry if I made things confusing.

**Comment by Ean-Warrick** [comment]
No problem, I'm the one who messed up the branches. I'll see if I can add the pins to the right branch tomorrow morning. I'll also try to get git directions to switch to the right branch from the professor for you. I forgot to mention the different branches in my email I sent.
